agent: "TD3"
env_name: "mujoco"
env_id: "Hopper-v4"
policy: "TD3_Policy"
representation: "Basic_Identical"

representation_hidden_size: [256,]
actor_hidden_size: [256, ]
critic_hidden_size: [256, ]
activation: "LeakyReLU"

seed: 1929
nsize: 50000
batchsize: 256
actor_learning_rate: 0.001
actor_update_decay: 3
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.01

start_noise: 0.5
end_noise: 0.01
training_frequency: 1
training_steps: 250000
start_training: 10000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

save_model_frequency: 10000
logdir: "./logs/td3/"
modeldir: "./models/td3/"