dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"

runner: "DRL"  # Choices: "DRL", "MARL", "Mean_Field_MARL"
project_name: "XuanPolicy_Benchmark"
logger: "wandb"  # Choices: tensorboard, wandb.
wandb_user_name: "wzliu"

parallels: 10
seed: 2910
vectorize: "Dummy"  # "Dummy" for DRL, "Dummy_MAS" for MARL
train_at_step: False  # True: train once after a step; False: train after an episode.
render: True
render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
render_delay: 0.02  # s
test_mode: False
test_steps: 2000

device: "cuda:0"

# PyTorch: "cpu", "cuda:0";
# TensorFlow: "cpu"/"CPU", "gpu"/"GPU";
# MindSpore: "CPU", "GPU", "Ascend", "Davinci"

