agent: "PPG"
env_name: "MuJoCo"
env_id: "InvertedPendulum-v2"
representation: "Basic_MLP"
policy: "Gaussian_PPG"

representation_hidden_size: [256,]
actor_hidden_size: [256,]
critic_hidden_size: [256,]
activation: "LeakyReLU"

parallels: 16
training_steps: 1000000  # 1M
nsteps: 256
nminibatch: 4
nepoch: 2
policy_nepoch: 2
value_nepoch: 4
aux_nepoch: 8

learning_rate: 0.0007

ent_coef: 0.0
clip_range: 0.25
kl_beta: 2.0
gamma: 0.98
lam: 0.95

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 5
logdir: "./logs/ppg/"
modeldir: "./models/ppg/"
