agent: "PG"
env_name: "mujoco"
env_id: "Hopper-v3"
policy: "Gaussian_Actor"
representation: "Basic_MLP"

representation_hidden_size: [256,]
actor_hidden_size: [256,]
activation: "LeakyReLU"

parallels: 16
training_steps: 62500
nsteps: 64
nepoch: 1
nminibatch: 1 
learning_rate: 0.0007

ent_coef: 0.0
clip_grad: 0.5
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
gamma: 0.99
lam: 0.95

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

save_model_frequency: 10000
logdir: "./logs/pg/"
modeldir: "./models/pg/"
