agent: "VDN"  # the learning algorithms_marl
env_name: "mpe"
env_id: "simple_spread_v3"
continuous_action: False
policy: "Mixing_Q_network"
representation: "Basic_MLP"
vectorize: "Dummy_Pettingzoo"
runner: "MPE_Runner"
on_policy: False

representation_hidden_size: [64, ]
q_hidden_size: [64, ]  # the units for each hidden layer
activation: "ReLU"

seed: 1
parallels: 128
buffer_size: 5000
batch_size: 32
learning_rate: 0.0007
gamma: 0.99  # discount factor

start_greedy: 0.0
end_greedy: 0.95
greedy_update_steps: 5000
training_steps: 2000000  # 2M
training_frequency: 1
sync_frequency: 100

n_tests: 5
double_q: True  # use double q learning

test_episodes: 10
eval_interval: 20000
test_episode: 5
logdir: "./logs/vdn/"
modeldir: "./models/vdn/"
