agent: "DQN"
env_name: "Classic Control"
env_id: "CartPole-v1"
policy: "Basic_Q_network"
representation: "Basic_MLP"

representation_hidden_size: [256,]
q_hidden_size: [256,]
activation: 'ReLU'

nsize: 20000
batchsize: 256
learning_rate: 0.001
gamma: 0.99

start_greedy: 0.5
end_greedy: 0.01
sync_frequency: 100
training_frequency: 2
training_steps: 30000
start_training: 1000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 1000
test_episode: 5
logdir: "./logs/dqn/"
modeldir: "./models/dqn/"
