agent: "PPO_Clip"
env_name: "MuJoCo"
env_id: "Ant-v4"
policy: "Gaussian_AC"
representation: "Basic_MLP"

representation_hidden_size: [256,]
actor_hidden_size: [256,]
critic_hidden_size: [256,]
activation: "LeakyReLU"

seed: 79811
parallels: 16
training_steps: 62500
nsteps: 256
nepoch: 16
nminibatch: 8
learning_rate: 0.0004

vf_coef: 0.25
ent_coef: 0.0
clip_range: 0.2
clip_grad_norm: 0.5
gamma: 0.99
lam: 0.95

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

save_model_frequency: 10000
logdir: "./logs/ppo/"
modeldir: "./models/ppo/"