agent: "A2C"
env_name: "Atari"
env_id: "ALE/Breakout-v5"
obs_type: "grayscale"  # choice for Atari env: ram, rgb, grayscale
img_size: [84, 84]  # default is 210 x 160 in gym[Atari]
num_stack: 4  # frame stack trick
frame_skip: 4  # frame skip trick
noop_max: 30  # Do no-op action for a number of steps in [1, noop_max].
policy: "Categorical_AC"
representation: "Basic_CNN"

# the following three arguments are for "Basic_CNN" representation.
filters: [16, 16, 32, 32]  # [32, 64, 64]
kernels: [8, 6, 4, 4]  # [8, 4, 3]
strides: [2, 2, 2, 2]  # [4, 2, 1]

actor_hidden_size: [256,]
critic_hidden_size: [256,]
activation: "LeakyReLU"

training_steps: 100000000  # 100e6
nsteps: 1024  #
nepoch: 2
nminibatch: 16
learning_rate: 0.0005
parallels: 8

vf_coef: 0.25
ent_coef: 0.01
clip_grad: 0.5
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
gamma: 0.98
lam: 0.95

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 100000
test_episode: 1
logdir: "./logs/a2c/"
modeldir: "./models/a2c/"