agent: "PPO_Clip"  # Choice: PPO_Clip, PPO_KL
env_name: "Box2D"
env_id: "BipedalWalker-v3"
representation: "Basic_MLP"
policy: "Gaussian_AC"

representation_hidden_size: [128,]
actor_hidden_size: [128,]
critic_hidden_size: [128,]
activation: 'LeakyReLU'

training_steps: 30000
nsteps: 256
nepoch: 8
nminibatch: 8
learning_rate: 0.0004

vf_coef: 0.25
ent_coef: 0.01
target_kl: 0.001  # for PPO_KL agent
clip_range: 0.2  # for PPO_Clip agent
gamma: 0.98
lam: 0.95

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 3
logdir: "./logs/ppo/"
modeldir: "./models/ppo/"