agent: "DRQN"  # deep recurrent Q-networks
env_name: "Classic Control"
env_id: "CartPole-v1"
policy: "DRQN_Policy"
representation: "Basic_MLP"
recurrent: "GRU"

representation_hidden_size: [128,]
recurrent_hidden_size: 128
recurrent_layer_N: 1
dropout: 0
activation: 'ReLU'

parallels: 10
max_episode_length: -1  # -1: set max_episode_length the same as the env's default value.
nsize: 100  # memory size for each parallel
batchsize: 16  # batch size for training
learning_rate: 0.001
gamma: 0.99

start_greedy: 0.5
end_greedy: 0.01
decay_episodes_greedy: 1000
sync_frequency: 50
training_frequency: 1
n_trains_per_episode: 2
training_steps: 2000  # number of training episodes
start_training: 100

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 1
logdir: "./logs/drqn/"
modeldir: "./models/drqn/"
