agent: "DDPG"
env_name: "mujoco"
env_id: "Ant-v4"
policy: "DDPG_Policy"
representation: "Basic_Identical"

representation_hidden_size: [256,]
actor_hidden_size: [256, ]
critic_hidden_size: [256, 1]

nsize: 50000
batchsize: 256
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.01
learning_rate: 0.0007

start_noise: 0.1
end_noise: 0.1
training_frequency: 1
training_steps: 250000
start_training: 10000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

logdir: "./logs/ddpg/"
modeldir: "./models/ddpg/"