agent: "DDPG"
env_name: "mujoco"
env_id: "Hopper-v3"
policy: "DDPG_Policy"
representation: "Basic_Identical"

representation_hidden_size: [256, ]  # If you choose Basic_Identical representation, then ignore this value
actor_hidden_size: [256, ]
critic_hidden_size: [256, 1]

seed: 3577
parallels: 4  # number of environments
nsize: 50000  # replay buffer size
batchsize: 256
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.01

start_noise: 0.1
end_noise: 0.1
training_frequency: 1
training_steps: 250000
start_training: 10000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

save_model_frequency: 10000
logdir: "./logs/ddpg/"
modeldir: "./models/ddpg/"