agent: "PG"
env_name: "MuJoCo"
env_id: "Ant-v4"
policy: "Gaussian_Actor"
representation: "Basic_MLP"

representation_hidden_size: [256,]
actor_hidden_size: [256,]
activation: "LeakyReLU"

parallels: 16
running_steps: 1000000  # 1M
nsteps: 256
nepoch: 1
nminibatch: 1 
learning_rate: 0.0007

ent_coef: 0.0
clip_grad: 0.5
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
gamma: 0.99
lam: 0.95

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 5
log_dir: "./logs/pg/"
model_dir: "./models/pg/"