agent: "C51DQN"  # Name of agent
env_name: "Classic Control"
env_id: "Acrobot-v1"
env_seed: 1  # Random seed for the environment.
vectorize: "DummyVecEnv"  # Method to vectorize the environment.
learner: "C51_Learner"  # Name of the learner.
policy: "C51_Q_network"  # Name of the policy.
representation: "Basic_MLP"
runner: "DRL"  # Name of the runner.

representation_hidden_size: [128,]
q_hidden_size: [128,]
activation: 'relu'

seed: 1
parallels: 10
buffer_size: 200000
batch_size: 256
learning_rate: 0.001
gamma: 0.99
v_min: 0
v_max: 200
atom_num: 51

start_greedy: 0.5
end_greedy: 0.01
decay_step_greedy: 100000
sync_frequency: 100
training_frequency: 1
running_steps: 300000
start_training: 1000

use_grad_clip: False  # gradient normalization
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: False  # Whether to use observation normalization trick.
use_rewnorm: False  # Whether to use reward normalization trick.
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 50000
test_episode: 1
log_dir: "./logs/c51/"  # The directory to store logger file.
model_dir: "./models/c51/"  # The directory to store model file.
