agent: "IQL"  # the learning algorithms_marl
env_name: "mpe"
env_id: "simple_spread_v3"
continuous_action: False
policy: "Basic_Q_network_marl"
representation: "Basic_MLP"
vectorize: "Dummy_Pettingzoo"
runner: "MPE_Runner"

representation_hidden_size: [64, ]  # the units for each hidden layer
q_hidden_size: [64, ]
activation: "ReLU"

parallels: 128
buffer_size: 100000
batch_size: 256
learning_rate: 0.0007
gamma: 0.95  # discount factor

start_greedy: 0.0
end_greedy: 0.95
greedy_update_steps: 5000
training_steps: 20000000  # 20M
start_training: 1000
training_frequency: 1
sync_frequency: 200

n_tests: 5
test_period: 100
double_q: True  # use double q learning

logdir: "./logs/iql/"
modeldir: "./models/iql/"
