agent: "DQN"
env_name: "Atari"
env_id: "ALE/Breakout-v5"
obs_type: "ram"
policy: "Basic_Q_network"
representation: "Basic_MLP"

representation_hidden_size: [256, 256]
q_hidden_size: [256,]
activation: 'ReLU'

nsize: 200000
batchsize: 256
learning_rate: 0.001
gamma: 0.99

start_greedy: 0.5
end_greedy: 0.01
sync_frequency: 100
training_frequency: 2
training_steps: 500000
start_training: 10000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

save_model_frequency: 10000
logdir: "./logs/dqn/"
modeldir: "./models/dqn/"
