agent: "PG"
env_name: "Classic Control"
env_id: "Acrobot-v1"
representation: "Basic_MLP"
policy: "Categorical_Actor"

representation_hidden_size: [128,]
actor_hidden_size: [128,]
activation: 'ReLU'

training_steps: 30000
nsteps: 500
nepoch: 1
nminibatch: 1
learning_rate: 0.0004

ent_coef: 0.01
clip_grad: 0.5
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
gamma: 0.98
lam: 0.95

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 1
logdir: "./logs/pg/"
modeldir: "./models/pg/"